### ISSUE TITLE
IRQ_SAFE in pimp_mixer_arm.S is borked

### ISSUE THREAD

**Issue by PoroCYon** [kusma/pimpmobile#5]
Compare:

https://github.com/kusma/pimpmobile/blob/master/src/pimp_mixer_arm.S#L61-L63

https://github.com/kusma/pimpmobile/blob/master/src/pimp_mixer_arm.S#L303

Also, `IRQ_SAFE` should maybe be made the default.

I might write a fix for this Soon™ (probably right after FOSDEM)

**Comment by kusma** [comment]
Whups, you're right, that's a bad slip-up.

And yeah, it's probably better to have the IRQ-safe version being the default. Good suggestion.
